Profile Page Prototype
jayyduran0108/CodeU-2018 pull request #3
Opened 2018-05-21 22:34 UTC by jayyduran0108

I created the ProfileServlet which grabs the username the user clicked on. I create the profile.jsp which verifies if the user is looking at their own profile or not.

2018-05-22 00:48 UTC, chilimalone requested changes
Good job! Please wait for reviews before merging your code in.  I've just a few nits

2018-05-22 00:48 UTC, chilimalone commented on src/main/webapp/WEB-INF/view/profile.jsp
> +<<%--
extra <

2018-05-22 00:48 UTC, chilimalone commented on src/main/java/codeu/controller/ProfileServlet.java
> +  /** Extract the URL
nit: remove dead code before you submit.

2018-05-22 00:48 UTC, chilimalone commented on src/main/java/codeu/controller/ProfileServlet.java
> +public class ProfileServlet extends HttpServlet {
nit: add new line before the class declaration

2018-05-22 00:48 UTC, chilimalone commented on src/main/java/codeu/controller/ProfileServlet.java
> +import org.jsoup.Jsoup;
nit: add newline before this to separate different library imports

2018-05-22 00:48 UTC, chilimalone commented on src/main/java/codeu/controller/ProfileServlet.java
> +import java.io.IOException;
nit: add newline before to separate library imports (for readability)

2018-05-22 00:48 UTC, chilimalone commented on src/main/java/codeu/controller/ProfileServlet.java
> +  /** Store class that gives access to Users. */
I think the existing code all uses 4 spaces for indent. Please use 4 spaces for consistency :)

2018-05-22 00:48 UTC, chilimalone commented on src/main/webapp/WEB-INF/view/profile.jsp
> +  Copyright 2017 Google Inc.
edit date?

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/webapp/WEB-INF/view/profile.jsp
> +<<%--
done

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/java/codeu/controller/ProfileServlet.java
> +  /** Extract the URL
done

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/java/codeu/controller/ProfileServlet.java
> +public class ProfileServlet extends HttpServlet {
done

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/java/codeu/controller/ProfileServlet.java
> +import org.jsoup.Jsoup;
done

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/java/codeu/controller/ProfileServlet.java
> +import java.io.IOException;
done

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/java/codeu/controller/ProfileServlet.java
> +  /** Store class that gives access to Users. */
done

2018-05-23 07:25 UTC, jayyduran0108 commented on src/main/webapp/WEB-INF/view/profile.jsp
> +  Copyright 2017 Google Inc.
done

2018-05-23 19:15 UTC, chilimalone commented
Hey, thanks for responding to my comments! Please push your changes to the branch and let me know so I can confirm that the changes are present and approve the merge :)

2018-05-27 03:28 UTC, annepham25 approved these changes

2018-05-29 18:13 UTC, merged