Anne admin page
jayyduran0108/CodeU-2018 pull request #6
Opened 2018-05-31 19:35 UTC by annepham25

So I realize that this pull request includes all of the insertions that I did (so all of the MVP stuff), but I'm not sure how to split it up into different pull requests... So, I'll just have this for now so you guys are able to see what I'm doing. Also, when I have time, I want to go back and tidy up the style and make it more efficient and improve the time complexity if possible.

What's been added:
   - hard coded list of who can access the admin page
   - showing the number of users
   - showing the number of convos
   - showing the number messages
   - shows the most active user
   - shows the most wordy user
   - shows the newest user
   - added an admin tab to each page

2018-05-31 21:42 UTC, chilimalone requested changes
Good job! Just a few stylistic comments

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +import codeu.model.store.persistence.PersistentDataStore;
alphabetize with the rest of codeu stuff

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +import java.io.IOException;
the ordering is:
<section for project specific imports, alphabetized>
<empty line>
<section for external libraries - i.e. org.mindrot.jbcrypt...>
<empty line>
<section for java imports, with java first and javax after>

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +
just 1 newline between sections

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +  /**
empty comment?

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/model/store/basic/MessageStore.java
> +    public List<Message> getAllMessages() {
only +2 space indent

2018-05-31 21:42 UTC, chilimalone commented on src/main/webapp/WEB-INF/view/admin.jsp
> +        <p> From source: </p>
-2 indent, this isn't under any tag

2018-05-31 21:42 UTC, chilimalone commented on src/main/webapp/WEB-INF/view/admin.jsp
> +        <button type="button">Submit</button>
ditto

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +import org.mindrot.jbcrypt.BCrypt;
this isn't used?

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +import java.util.*;
don't import both java.util.* and java.util.List

prefer to list each class individually rather than download the whole util package

2018-05-31 21:42 UTC, chilimalone commented on src/main/java/codeu/controller/AdminServlet.java
> +import java.time.Instant;
this isn't used? Remove unused imports

2018-05-31 23:17 UTC, Georgeg10499 requested changes
Nice Code! but only a few comments

2018-05-31 23:17 UTC, Georgeg10499 commented on src/main/webapp/WEB-INF/web.xml
> +
-1 space

2018-05-31 23:17 UTC, Georgeg10499 commented on src/main/java/codeu/controller/AdminServlet.java
> +
-1 space

2018-05-31 23:17 UTC, Georgeg10499 commented on src/main/java/codeu/controller/AdminServlet.java
> +
-1 space

2018-06-01 06:51 UTC, jayyduran0108 requested changes
Looks good!

2018-06-01 06:51 UTC, jayyduran0108 commented on src/main/java/codeu/controller/AdminServlet.java
> +import java.util.UUID;
I think this is added twice

2018-06-18 23:47 UTC, merged